export const typeOfTask: string[] = [
    'Project Planning and Design',
    'Site Preparation',
    'Foundation Construction',
    'Structural Framework',
    'Exterior Work',
    'Interior Work',
    'Utilities and Systems',
    'Finishing',
    'Exterior and Landscape',
    'Final Inspections and Certifications',
    'Handover and Occupancy'
];

export const typeOfProject: string[] = [
    'Single-Family Homes',
    'Apartments',
    'Townhouses',
    'Condominiums',
    'Gated Communities',
    'Office Buildings',
    'Retail Spaces',
    'Shopping Centers',
    'Hotels',
    'Warehouses',
    'Industrial Parks',
    'Apartments',
    'Offices',
    'Retail Stores',
    'Restaurants',
    'Industrial Parks',
    'Factories',
    'Logistics Centers',
    'Data Centers',
    'Hotels',
    'Resorts',
    'Serviced Apartments',
    'Vacation Rentals',
    'Airports',
    'Seaports',
    'Roads',
    'Bridges',
    'Railways',
    'Urban Renewal',
    'Adaptive Reuse',
    'Revitalization',
    'Subsidized Housing',
    'Social Housing',
    'Affordable Rental Units',
    'Premium Residential Properties',
    'Luxury Condominiums',
    'High-Rise Penthouses',
    'Exclusive Gated Communities',
    'Residential Development',
    'Commercial Development',
    'Real Estate Funds',
    'REITs',
    'Property Flipping'
];
